version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - Attributify
  - birpc
  - composables
  - luby
  - Nuxt
  - pako
  - Positionals
  - qifi
  - QRCODE
  - Soliton
  - timeseries
  - unocss
  - wechat
ignoreWords: []
import: []
